// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMHwhlCRDKCWbaETcRlGL83WDD1P16YUk',
    appId: '1:1051720751921:web:a240fc349fc77327ea2e10',
    messagingSenderId: '1051720751921',
    projectId: 'lotso-app',
    authDomain: 'lotso-app.firebaseapp.com',
    storageBucket: 'lotso-app.firebasestorage.app',
    measurementId: 'G-JQ7N8YKXJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2mJa8APsp36vYdwKTnAk_NDxP2IsxV4g',
    appId: '1:1051720751921:android:c120def522c72b69ea2e10',
    messagingSenderId: '1051720751921',
    projectId: 'lotso-app',
    storageBucket: 'lotso-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wQ4T1ugVL_OJFGQRWSMNOqAL4AdcC3U',
    appId: '1:1051720751921:ios:3e06bbd13300fb73ea2e10',
    messagingSenderId: '1051720751921',
    projectId: 'lotso-app',
    storageBucket: 'lotso-app.firebasestorage.app',
    iosBundleId: 'com.example.lotsoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5wQ4T1ugVL_OJFGQRWSMNOqAL4AdcC3U',
    appId: '1:1051720751921:ios:3e06bbd13300fb73ea2e10',
    messagingSenderId: '1051720751921',
    projectId: 'lotso-app',
    storageBucket: 'lotso-app.firebasestorage.app',
    iosBundleId: 'com.example.lotsoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMHwhlCRDKCWbaETcRlGL83WDD1P16YUk',
    appId: '1:1051720751921:web:4b414ec0eef814edea2e10',
    messagingSenderId: '1051720751921',
    projectId: 'lotso-app',
    authDomain: 'lotso-app.firebaseapp.com',
    storageBucket: 'lotso-app.firebasestorage.app',
    measurementId: 'G-G553KD2SVM',
  );
}
